name: release
on:
  push:
    tags:
      - '*'
jobs:
  binaries:
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: make dep
      - name: Run lint
        run: make release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            APP_VERSION=${{ github.ref_name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
